-- AlterTable
ALTER TABLE `users` MODIFY `role` ENUM('PLAYER', 'SOBREVIVENTE', 'PREMIUM', 'BETA_TESTER', 'YOUTUBER', 'SUPORTE', 'ESTAGIARIO', 'MODERADOR', 'ADMINISTRADOR', 'SUPERVISOR', 'COORDENADOR', 'GERENTE', 'SUB_DIRETOR', 'DIRETOR', 'DESENVOLVEDOR', 'STAFF', 'ADMIN', 'OWNER') NOT NULL DEFAULT 'SOBREVIVENTE';
