ALTER TABLE `users`
  ADD COLUMN `zCoins` INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN `gameLevel` INTEGER NOT NULL DEFAULT 1,
  ADD COLUMN `gameXp` INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN `vipTier` VARCHAR(191) NULL,
  ADD COLUMN `clanName` VARCHAR(191) NULL,
  ADD COLUMN `kills` INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN `deaths` INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN `playtimeMinutes` INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN `lastGameLogin` DATETIME(3) NULL,
  ADD COLUMN `isOnlineInGame` BOOLEAN NOT NULL DEFAULT false;
